#!/bin/sh
export R_HOME=/usr/lib/R
XLISPLIB=/home/jtan/Apps/xlisp/lib/xlispstat export XLISPLIB
if test -f xlisp.wks; then WKS="xlisp.wks";
else WKS="${XLISPLIB}/xlisp.wks";
fi
if test -f xlisp; then XLISP=./xlisp;
else XLISP="${XLISPLIB}/xlisp"
fi
exec ${XLISP} -w${WKS} $*
